# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - FlavorFusion

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
<<<<<<< HEAD
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
=======
          node-version: "20.x"

      - name: npm install, build, and test
        run: |
          npm install --workspaces=false
          npm run -w express-backend build --if-present
          npm run -w express-backend test --if-present
        working-directory: packages/express-backend

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r
        working-directory: packages/express-backend
>>>>>>> 4874ddc46a8220c4dbb11b443ff9bc3bd3f9b15f

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
<<<<<<< HEAD
          path: release.zip
=======
          path: packages/express-backend/release.zip
>>>>>>> 4874ddc46a8220c4dbb11b443ff9bc3bd3f9b15f

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
<<<<<<< HEAD
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
=======
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
>>>>>>> 4874ddc46a8220c4dbb11b443ff9bc3bd3f9b15f

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
<<<<<<< HEAD
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_699F2E19173247D4847B61CC6180EA3D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_333DBFC7B21042B5B9D5D765AD0D795C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FEF1B0AAC73A4A8E86FBA12A85C1BD5E }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'FlavorFusion'
          slot-name: 'Production'
          package: .
          
=======

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_699F2E19173247D4847B61CC6180EA3D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_333DBFC7B21042B5B9D5D765AD0D795C }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FEF1B0AAC73A4A8E86FBA12A85C1BD5E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "FlavorFusion"
          slot-name: "Production"
          package: .
>>>>>>> 4874ddc46a8220c4dbb11b443ff9bc3bd3f9b15f
